//data from  https://en.uesp.net/wiki/Skyrim:Ingredients
//data from  https://steamcommunity.com/sharedfiles/filedetails/?id=1378262872
//data from  https://wiki.biligame.com/skyrim/%E7%82%BC%E9%87%91%E6%95%88%E6%9E%9C
//参考中英文词汇表 https://wiki.biligame.com/skyrim/%E4%B8%8A%E5%8F%A4%E5%8D%B7%E8%BD%B45%E5%A4%A9%E9%99%85:%E8%AF%8D%E6%B1%87%E8%A1%A8/%E6%A4%8D%E7%89%A9%E5%92%8C%E7%82%BC%E9%87%91
//控制台 player.additem 代码 数量
//代码前面的xx 表示mod序号 01-99 根据不同的电脑mod载入顺序不同而不同,所以需要尝试
//FExxx  中的 xxx也表示 001-999 根据电脑mod顺序不同而不同

//如果更新了数据请删除 recipeCache.json

var G_data = [
    {
        "name": "Abecean Longfin",
        "name_zh": "阿贝希恩长鳍鱼, 阿碧希恩长鳍鱼",
        "img": "jsimgcss\/img\/0.png",
        "code": "00106e1b", //控制台代码
        "price": 15, //满级价格
        "weight": 0.5, //重量
        "store": "常见", //商店是否常见
        "garden": "", //是否可以在花园中种植(数字含义不详)
        "e1": "Weakness to Frost", //效果1
        "m1": 1, //效果倍率
        "v1": 1, //价值倍率
        "d1": 1, //等待时间倍率
        "e2": "Fortify Sneak",
        "m2": 1,
        "v2": 1,
        "d2": 1,
        "e3": "Weakness to Poison",
        "m3": 1,
        "v3": 1,
        "d3": 1,
        "e4": "Fortify Restoration",
        "m4": 1,
        "v4": 1,
        "d4": 1
    },
    {
        "name": "Aloe Vera Leaves",
        "name_zh": "芦荟叶",
        "img": "jsimgcss\/img\/1.png",
        "code": "FExxx0D0",
        "price": 1,
        "weight": 0.1,
        "store": "卡吉特商人",
        "garden": "2",
        "e1": "Restore Health",
        "m1": 1,
        "v1": 1,
        "d1": 1,
        "e2": "Restore Stamina",
        "m2": 1,
        "v2": 1,
        "d2": 1,
        "e3": "Damage Magicka",
        "m3": 1,
        "v3": 1,
        "d3": 1,
        "e4": "Invisibility",
        "m4": 1,
        "v4": 1,
        "d4": 1
    },
    {
        "name": "Ancestor Moth Wing",
        "name_zh": "先祖蛾翅膀",
        "img": "jsimgcss\/img\/2.png",
        "code": "xx0059ba",
        "price": 2,
        "weight": 0.1,
        "store": "无",
        "garden": "",
        "e1": "Damage Stamina",
        "m1": 1,
        "v1": 1,
        "d1": 1,
        "e2": "Fortify Conjuration",
        "m2": 1,
        "v2": 1,
        "d2": 1,
        "e3": "Damage Magicka Regen",
        "m3": 1,
        "v3": 1,
        "d3": 1,
        "e4": "Fortify Enchanting",
        "m4": 1,
        "v4": 1,
        "d4": 1
    },
    {
        "name": "Ash Creep Cluster",
        "name_zh": "灰烬藤蔓丛",
        "img": "jsimgcss\/img\/3.png",
        "code": "xx01cd74",
        "price": 20,
        "weight": 0.25,
        "store": "稀有",
        "garden": "",
        "e1": "Damage Stamina",
        "m1": 1,
        "v1": 1,
        "d1": 1,
        "e2": "Invisibility",
        "m2": 1,
        "v2": 1,
        "d2": 1,
        "e3": "Resist Fire",
        "m3": 1,
        "v3": 1,
        "d3": 1,
        "e4": "Fortify Destruction",
        "m4": 1,
        "v4": 1,
        "d4": 1
    },
    {
        "name": "Ash Hopper Jelly",
        "name_zh": "灰烬跳蚤肉冻",
        "img": "jsimgcss\/img\/4.png",
        "code": "xx01cd71",
        "price": 20,
        "weight": 0.25,
        "store": "",
        "garden": "",
        "e1": "Restore Health",
        "m1": 1,
        "v1": 1,
        "d1": 1,
        "e2": "Fortify Light Armor",
        "m2": 1,
        "v2": 1,
        "d2": 1,
        "e3": "Resist Shock",
        "m3": 1,
        "v3": 1,
        "d3": 1,
        "e4": "Weakness to Frost",
        "m4": 1,
        "v4": 1,
        "d4": 1
    },
    {
        "name": "Ashen Grass Pod",
        "name_zh": "灰色豆荚,灰烬草种荚",
        "img": "jsimgcss\/img\/5.png",
        "code": "xx016e26",
        "price": 1,
        "weight": 0.1,
        "store": "",
        "garden": "",
        "e1": "Resist Fire",
        "m1": 1.33,
        "v1": 1.36,
        "d1": 1,
        "e2": "Weakness to Shock",
        "m2": 1,
        "v2": 1,
        "d2": 1,
        "e3": "Fortify Lockpicking",
        "m3": 1,
        "v3": 1,
        "d3": 1,
        "e4": "Fortify Sneak",
        "m4": 1,
        "v4": 1,
        "d4": 1
    },
    {
        "name": "Bear Claws",
        "name_zh": "熊爪",
        "img": "jsimgcss\/img\/6.png",
        "code": "0006bc02",
        "price": 2,
        "weight": 0.1,
        "store": "无",
        "garden": "",
        "e1": "Restore Stamina",
        "m1": 0.8,
        "v1": 0.78,
        "d1": 1,
        "e2": "Fortify Health",
        "m2": 1,
        "v2": 1,
        "d2": 1,
        "e3": "Fortify One-handed",
        "m3": 1,
        "v3": 1,
        "d3": 1,
        "e4": "Damage Magicka Regen",
        "m4": 1,
        "v4": 1,
        "d4": 1
    },
    {
        "name": "Bee",
        "name_zh": "蜜蜂",
        "img": "jsimgcss\/img\/7.png",
        "code": "000a9195",
        "price": 3,
        "weight": 0.1,
        "store": "常见",
        "garden": "",
        "e1": "Restore Stamina",
        "m1": 1,
        "v1": 1,
        "d1": 1,
        "e2": "Ravage Stamina",
        "m2": 1,
        "v2": 1,
        "d2": 1,
        "e3": "Regenerate Stamina",
        "m3": 1,
        "v3": 1,
        "d3": 1,
        "e4": "Weakness to Shock",
        "m4": 1,
        "v4": 1,
        "d4": 1
    },
    {
        "name": "Beehive Husk",
        "name_zh": "蜂箱外壳",
        "img": "jsimgcss\/img\/8.png",
        "code": "000a9191",
        "price": 5,
        "weight": 1,
        "store": "无",
        "garden": "",
        "e1": "Resist Poison",
        "m1": 0.5,
        "v1": 1,
        "d1": 1,
        "e2": "Fortify Light Armor",
        "m2": 1,
        "v2": 1,
        "d2": 1,
        "e3": "Fortify Sneak",
        "m3": 1,
        "v3": 1,
        "d3": 1,
        "e4": "Fortify Destruction",
        "m4": 1,
        "v4": 1,
        "d4": 1
    },
    {
        "name": "Bleeding Crown",
        "name_zh": "鲜血王冠",
        "img": "jsimgcss\/img\/9.png",
        "code": "0004da20",
        "price": 10,
        "weight": 0.3,
        "store": "不常见",
        "garden": "3",
        "e1": "Weakness to Fire",
        "m1": 1,
        "v1": 1,
        "d1": 1,
        "e2": "Fortify Block",
        "m2": 1,
        "v2": 1,
        "d2": 1,
        "e3": "Weakness to Poison",
        "m3": 1,
        "v3": 1,
        "d3": 1,
        "e4": "Resist Magic",
        "m4": 1,
        "v4": 1,
        "d4": 1
    },
    {
        "name": "Blisterwort",
        "name_zh": "气泡草",
        "img": "jsimgcss\/img\/10.png",
        "code": "0004da25",
        "price": 12,
        "weight": 0.2,
        "store": "不常见",
        "garden": "4",
        "e1": "Damage Stamina",
        "m1": 1,
        "v1": 1,
        "d1": 1,
        "e2": "Frenzy",
        "m2": 1,
        "v2": 1,
        "d2": 1,
        "e3": "Restore Health",
        "m3": 0.6,
        "v3": 0.57,
        "d3": 1,
        "e4": "Fortify Smithing",
        "m4": 1,
        "v4": 1,
        "d4": 1
    },
    {
        "name": "Blue Butterfly Wing",
        "name_zh": "蓝蝶翅膀",
        "img": "jsimgcss\/img\/11.png",
        "code": "000727de",
        "price": 2,
        "weight": 0.1,
        "store": "不常见",
        "garden": "",
        "e1": "Damage Stamina",
        "m1": 1,
        "v1": 1,
        "d1": 1,
        "e2": "Fortify Conjuration",
        "m2": 1,
        "v2": 1,
        "d2": 1,
        "e3": "Damage Magicka Regen",
        "m3": 1,
        "v3": 1,
        "d3": 1,
        "e4": "Fortify Enchanting",
        "m4": 1,
        "v4": 1,
        "d4": 1
    },
    {
        "name": "Blue Dartwing",
        "name_zh": "蓝色飞虫, 蓝色飞翼",
        "img": "jsimgcss\/img\/12.png",
        "code": "000e4f0c",
        "price": 1,
        "weight": 0.1,
        "store": "无",
        "garden": "",
        "e1": "Resist Shock",
        "m1": 1,
        "v1": 1,
        "d1": 1,
        "e2": "Fortify Pickpocket",
        "m2": 1,
        "v2": 1,
        "d2": 1,
        "e3": "Restore Health",
        "m3": 1,
        "v3": 1,
        "d3": 1,
        "e4": "Fear",
        "m4": 1,
        "v4": 1,
        "d4": 1
    },
    {
        "name": "Blue Mountain Flower",
        "name_zh": "蓝山花",
        "img": "jsimgcss\/img\/13.png",
        "code": "00077e1c",
        "price": 2,
        "weight": 0.1,
        "store": "常见",
        "garden": "3",
        "e1": "Restore Health",
        "m1": 1,
        "v1": 1,
        "d1": 1,
        "e2": "Fortify Conjuration",
        "m2": 1,
        "v2": 1,
        "d2": 1,
        "e3": "Fortify Health",
        "m3": 1,
        "v3": 1,
        "d3": 1,
        "e4": "Damage Magicka Regen",
        "m4": 1,
        "v4": 1,
        "d4": 1
    },
    {
        "name": "Boar Tusk",
        "name_zh": "野猪牙",
        "img": "jsimgcss\/img\/14.png",
        "code": "xx01cd6f",
        "price": 20,
        "weight": 0.5,
        "store": "",
        "garden": "",
        "e1": "Fortify Stamina",
        "m1": 1.25,
        "v1": 7.5,
        "d1": 5,
        "e2": "Fortify Health",
        "m2": 1,
        "v2": 5.9,
        "d2": 5,
        "e3": "Fortify Block",
        "m3": 1,
        "v3": 1,
        "d3": 1,
        "e4": "Frenzy",
        "m4": 1,
        "v4": 1,
        "d4": 1
    },
    {
        "name": "Bone Meal",
        "name_zh": "骨粉",
        "img": "jsimgcss\/img\/15.png",
        "code": "00034cdd",
        "price": 5,
        "weight": 0.5,
        "store": "常见",
        "garden": "",
        "e1": "Damage Stamina",
        "m1": 1,
        "v1": 1,
        "d1": 1,
        "e2": "Resist Fire",
        "m2": 1,
        "v2": 1,
        "d2": 1,
        "e3": "Fortify Conjuration",
        "m3": 1,
        "v3": 1,
        "d3": 1,
        "e4": "Ravage Stamina",
        "m4": 1,
        "v4": 1,
        "d4": 1
    },
    {
        "name": "Briar Heart",
        "name_zh": "荆棘之心",
        "img": "jsimgcss\/img\/16.png",
        "code": "0003ad61",
        "price": 20,
        "weight": 0.5,
        "store": "稀有",
        "garden": "",
        "e1": "Restore Magicka",
        "m1": 1,
        "v1": 1,
        "d1": 1,
        "e2": "Fortify Block",
        "m2": 0.5,
        "v2": 1,
        "d2": 1,
        "e3": "Paralysis",
        "m3": 1,
        "v3": 1,
        "d3": 1,
        "e4": "Fortify Magicka",
        "m4": 1,
        "v4": 1,
        "d4": 1
    },
    {
        "name": "Burnt Spriggan Wood",
        "name_zh": "燃烧树精之木",
        "img": "jsimgcss\/img\/17.png",
        "code": "xx01cd6e",
        "price": 20,
        "weight": 0.5,
        "store": "",
        "garden": "",
        "e1": "Weakness to Fire",
        "m1": 1,
        "v1": 1,
        "d1": 1,
        "e2": "Fortify Alteration",
        "m2": 1,
        "v2": 1,
        "d2": 1,
        "e3": "Damage Magicka Regen",
        "m3": 1,
        "v3": 1,
        "d3": 1,
        "e4": "Slow",
        "m4": 1,
        "v4": 1,
        "d4": 1
    },
    {
        "name": "Butterfly Wing",
        "name_zh": "蝴蝶翅膀, 帝王蝶翅膀",
        "img": "jsimgcss\/img\/18.png",
        "code": "000727e0",
        "price": 3,
        "weight": 0.1,
        "store": "不常见",
        "garden": "",
        "e1": "Restore Health",
        "m1": 1,
        "v1": 1,
        "d1": 1,
        "e2": "Fortify Barter",
        "m2": 1,
        "v2": 1,
        "d2": 1,
        "e3": "Lingering Damage Stamina",
        "m3": 1,
        "v3": 1,
        "d3": 1,
        "e4": "Damage Magicka",
        "m4": 1,
        "v4": 1,
        "d4": 1
    },
    {
        "name": "Canis Root",
        "name_zh": "犬根, 犬型根",
        "img": "jsimgcss\/img\/19.png",
        "code": "0006abcb",
        "price": 5,
        "weight": 0.1,
        "store": "不常见",
        "garden": "4",
        "e1": "Damage Stamina",
        "m1": 1,
        "v1": 1,
        "d1": 1,
        "e2": "Fortify One-handed",
        "m2": 1,
        "v2": 1,
        "d2": 1,
        "e3": "Fortify Marksman",
        "m3": 1,
        "v3": 1,
        "d3": 1,
        "e4": "Paralysis",
        "m4": 1,
        "v4": 1,
        "d4": 1
    },
    {
        "name": "Charred Skeever Hide",
        "name_zh": "焦黑恶鼠皮, 烧焦的雪鼠毛皮",
        "img": "jsimgcss\/img\/20.png",
        "code": "00052695",
        "price": 1,
        "weight": 0.5,
        "store": "不常见",
        "garden": "",
        "e1": "Restore Stamina",
        "m1": 1,
        "v1": 1,
        "d1": 1,
        "e2": "Cure Disease",
        "m2": 1,
        "v2": 0.36,
        "d2": 1,
        "e3": "Resist Poison",
        "m3": 1,
        "v3": 1,
        "d3": 1,
        "e4": "Restore Health",
        "m4": 1,
        "v4": 1,
        "d4": 1
    },
    {
        "name": "Chaurus Eggs",
        "name_zh": "巢蚁卵, 查鲁斯之卵",
        "img": "jsimgcss\/img\/21.png",
        "code": "0003ad56",
        "price": 10,
        "weight": 0.2,
        "store": "不常见",
        "garden": "",
        "e1": "Weakness to Poison",
        "m1": 1,
        "v1": 1,
        "d1": 1,
        "e2": "Fortify Stamina",
        "m2": 1,
        "v2": 1,
        "d2": 1,
        "e3": "Damage Magicka",
        "m3": 1,
        "v3": 1,
        "d3": 1,
        "e4": "Invisibility",
        "m4": 1,
        "v4": 1,
        "d4": 1
    },
    {
        "name": "Chaurus Hunter Antennae",
        "name_zh": "巢蚁猎人触角",
        "img": "jsimgcss\/img\/22.png",
        "code": "xx0183b7",
        "price": 2,
        "weight": 0.1,
        "store": "无",
        "garden": "",
        "e1": "Damage Stamina",
        "m1": 1,
        "v1": 1,
        "d1": 1,
        "e2": "Fortify Conjuration",
        "m2": 1,
        "v2": 1,
        "d2": 1,
        "e3": "Damage Magicka Regen",
        "m3": 1,
        "v3": 1,
        "d3": 1,
        "e4": "Fortify Enchanting",
        "m4": 1,
        "v4": 1,
        "d4": 1
    },
    {
        "name": "Chicken's Egg",
        "name_zh": "鸡蛋",
        "img": "jsimgcss\/img\/23.png",
        "code": "00023d77",
        "price": 2,
        "weight": 0.5,
        "store": "不常见",
        "garden": "",
        "e1": "Resist Magic",
        "m1": 1,
        "v1": 1,
        "d1": 1,
        "e2": "Damage Magicka Regen",
        "m2": 1,
        "v2": 1,
        "d2": 1,
        "e3": "Waterbreathing",
        "m3": 1,
        "v3": 1,
        "d3": 1,
        "e4": "Lingering Damage Stamina",
        "m4": 1,
        "v4": 1,
        "d4": 1
    },
    {
        "name": "Creep Cluster",
        "name_zh": "藤蔓丛",
        "img": "jsimgcss\/img\/24.png",
        "code": "000b2183",
        "price": 1,
        "weight": 0.2,
        "store": "不常见",
        "garden": "5",
        "e1": "Restore Magicka",
        "m1": 1,
        "v1": 1,
        "d1": 1,
        "e2": "Damage Stamina Regen",
        "m2": 1,
        "v2": 1,
        "d2": 1,
        "e3": "Fortify Carry Weight",
        "m3": 1,
        "v3": 1,
        "d3": 1,
        "e4": "Weakness to Magic",
        "m4": 1,
        "v4": 1,
        "d4": 1
    },
    {
        "name": "Crimson Nirnroot",
        "name_zh": "深红奈恩根, 腥红奈恩根",
        "img": "jsimgcss\/img\/25.png",
        "code": "000b701a",
        "price": 10,
        "weight": 0.2,
        "store": "无",
        "garden": "",
        "e1": "Damage Health",
        "m1": 3,
        "v1": 1,
        "d1": 1,
        "e2": "Damage Stamina",
        "m2": 3,
        "v2": 1,
        "d2": 1,
        "e3": "Invisibility",
        "m3": 1,
        "v3": 1,
        "d3": 1,
        "e4": "Resist Magic",
        "m4": 1,
        "v4": 1,
        "d4": 1
    },
    {
        "name": "Cyrodilic Spadetail",
        "name_zh": "赛瑞迪尔斗鱼, 赛洛迪尔斗鱼",
        "img": "jsimgcss\/img\/26.png",
        "code": "00106e19",
        "price": 15,
        "weight": 0.25,
        "store": "常见",
        "garden": "",
        "e1": "Damage Stamina",
        "m1": 1,
        "v1": 1,
        "d1": 1,
        "e2": "Fortify Restoration",
        "m2": 1,
        "v2": 1,
        "d2": 1,
        "e3": "Fear",
        "m3": 1,
        "v3": 1,
        "d3": 1,
        "e4": "Ravage Health",
        "m4": 1,
        "v4": 1,
        "d4": 1
    },
    {
        "name": "Daedra Heart",
        "name_zh": "魔族心脏",
        "img": "jsimgcss\/img\/27.png",
        "code": "0003ad5b",
        "price": 250,
        "weight": 0.5,
        "store": "稀有",
        "garden": "",
        "e1": "Restore Health",
        "m1": 1,
        "v1": 1,
        "d1": 1,
        "e2": "Damage Stamina Regen",
        "m2": 1,
        "v2": 1,
        "d2": 1,
        "e3": "Damage Magicka",
        "m3": 1,
        "v3": 1,
        "d3": 1,
        "e4": "Fear",
        "m4": 1,
        "v4": 1,
        "d4": 1
    },
    {
        "name": "Deathbell",
        "name_zh": "丧钟花, 死亡丧钟",
        "img": "jsimgcss\/img\/28.png",
        "code": "000516c8",
        "price": 4,
        "weight": 0.1,
        "store": "稀有",
        "garden": "3",
        "e1": "Damage Health",
        "m1": 1.5,
        "v1": 1,
        "d1": 1,
        "e2": "Ravage Stamina",
        "m2": 1,
        "v2": 2.1,
        "d2": 1,
        "e3": "Slow",
        "m3": 1,
        "v3": 1,
        "d3": 1,
        "e4": "Weakness to Poison",
        "m4": 1,
        "v4": 1,
        "d4": 1
    },
    {
        "name": "Dragon's Tongue",
        "name_zh": "龙舌兰",
        "img": "jsimgcss\/img\/29.png",
        "code": "000889a2",
        "price": 5,
        "weight": 0.1,
        "store": "常见",
        "garden": "4",
        "e1": "Resist Fire",
        "m1": 1,
        "v1": 1,
        "d1": 1,
        "e2": "Fortify Barter",
        "m2": 1,
        "v2": 1,
        "d2": 1,
        "e3": "Fortify Illusion",
        "m3": 1,
        "v3": 1,
        "d3": 1,
        "e4": "Fortify Two-handed",
        "m4": 1,
        "v4": 1,
        "d4": 1
    },
    {
        "name": "Dwarven Oil",
        "name_zh": "矮人油",
        "img": "jsimgcss\/img\/30.png",
        "code": "000f11c0",
        "price": 15,
        "weight": 0.25,
        "store": "不常见",
        "garden": "",
        "e1": "Weakness to Magic",
        "m1": 1,
        "v1": 1,
        "d1": 1,
        "e2": "Fortify Illusion",
        "m2": 1,
        "v2": 1,
        "d2": 1,
        "e3": "Regenerate Magicka",
        "m3": 1,
        "v3": 1,
        "d3": 1,
        "e4": "Restore Magicka",
        "m4": 1,
        "v4": 1,
        "d4": 1
    },
    {
        "name": "Ectoplasm",
        "name_zh": "灵质, 灵皮",
        "img": "jsimgcss\/img\/31.png",
        "code": "0003ad63",
        "price": 25,
        "weight": 0.1,
        "store": "不常见",
        "garden": "",
        "e1": "Restore Magicka",
        "m1": 1,
        "v1": 1,
        "d1": 1,
        "e2": "Fortify Destruction",
        "m2": 0.8,
        "v2": 1,
        "d2": 1,
        "e3": "Fortify Magicka",
        "m3": 1,
        "v3": 1,
        "d3": 1,
        "e4": "Damage Health",
        "m4": 1,
        "v4": 1,
        "d4": 1
    },
    {
        "name": "Elves Ear",
        "name_zh": "精灵耳",
        "img": "jsimgcss\/img\/32.png",
        "code": "00034d31",
        "price": 10,
        "weight": 0.1,
        "store": "常见",
        "garden": "",
        "e1": "Restore Magicka",
        "m1": 1,
        "v1": 1,
        "d1": 1,
        "e2": "Fortify Marksman",
        "m2": 1,
        "v2": 1,
        "d2": 1,
        "e3": "Weakness to Frost",
        "m3": 1,
        "v3": 1,
        "d3": 1,
        "e4": "Resist Fire",
        "m4": 1,
        "v4": 1,
        "d4": 1
    },
    {
        "name": "Emperor Parasol Moss",
        "name_zh": "帝王伞苔",
        "img": "jsimgcss\/img\/33.png",
        "code": "xx01ff75",
        "price": 1,
        "weight": 0.25,
        "store": "",
        "garden": "",
        "e1": "Damage Health",
        "m1": 1.5,
        "v1": 1,
        "d1": 1,
        "e2": "Fortify Magicka",
        "m2": 1,
        "v2": 1,
        "d2": 1,
        "e3": "Regenerate Health",
        "m3": 1,
        "v3": 1,
        "d3": 1,
        "e4": "Fortify Two-handed",
        "m4": 1,
        "v4": 1,
        "d4": 1
    },
    {
        "name": "Eye of Sabre Cat",
        "name_zh": "剑齿虎之眼",
        "img": "jsimgcss\/img\/34.png",
        "code": "0006bc07",
        "price": 2,
        "weight": 0.1,
        "store": "无",
        "garden": "",
        "e1": "Restore Stamina",
        "m1": 1,
        "v1": 1,
        "d1": 1,
        "e2": "Ravage Health",
        "m2": 1,
        "v2": 1,
        "d2": 1,
        "e3": "Damage Magicka",
        "m3": 1,
        "v3": 1,
        "d3": 1,
        "e4": "Restore Health",
        "m4": 1,
        "v4": 1,
        "d4": 1
    },
    {
        "name": "Falmer Ear",
        "name_zh": "伐莫族的耳朵, 雪精灵耳",
        "img": "jsimgcss\/img\/35.png",
        "code": "0003ad5d",
        "price": 10,
        "weight": 0.2,
        "store": "不常见",
        "garden": "",
        "e1": "Damage Health",
        "m1": 1,
        "v1": 1,
        "d1": 1,
        "e2": "Frenzy",
        "m2": 1,
        "v2": 1,
        "d2": 1,
        "e3": "Resist Poison",
        "m3": 1,
        "v3": 1,
        "d3": 1,
        "e4": "Fortify Lockpicking",
        "m4": 1,
        "v4": 1,
        "d4": 1
    },
    {
        "name": "Felsaad Tern Feathers",
        "name_zh": "法萨德燕鸥羽毛",
        "img": "jsimgcss\/img\/36.png",
        "code": "xx03cd8e",
        "price": 15,
        "weight": 0.1,
        "store": "",
        "garden": "",
        "e1": "Restore Health",
        "m1": 1,
        "v1": 1,
        "d1": 1,
        "e2": "Fortify Light Armor",
        "m2": 1,
        "v2": 1,
        "d2": 1,
        "e3": "Cure Disease",
        "m3": 1,
        "v3": 1,
        "d3": 1,
        "e4": "Resist Magic",
        "m4": 1,
        "v4": 1,
        "d4": 1
    },
    {
        "name": "Fire Salts",
        "name_zh": "火盐",
        "img": "jsimgcss\/img\/37.png",
        "code": "0003ad5e",
        "price": 50,
        "weight": 0.25,
        "store": "稀有",
        "garden": "",
        "e1": "Weakness to Frost",
        "m1": 1,
        "v1": 1,
        "d1": 1,
        "e2": "Resist Fire",
        "m2": 1,
        "v2": 1,
        "d2": 1,
        "e3": "Restore Magicka",
        "m3": 1,
        "v3": 1,
        "d3": 1,
        "e4": "Regenerate Magicka",
        "m4": 1,
        "v4": 1,
        "d4": 1
    },
    {
        "name": "Fly Amanita",
        "name_zh": "毒蝇伞, 飞天菌菇",
        "img": "jsimgcss\/img\/38.png",
        "code": "0004da00",
        "price": 2,
        "weight": 0.1,
        "store": "不常见",
        "garden": "4",
        "e1": "Resist Fire",
        "m1": 1,
        "v1": 1,
        "d1": 1,
        "e2": "Fortify Two-handed",
        "m2": 1,
        "v2": 1,
        "d2": 1,
        "e3": "Frenzy",
        "m3": 1,
        "v3": 1,
        "d3": 1,
        "e4": "Regenerate Stamina",
        "m4": 1,
        "v4": 1,
        "d4": 1
    },
    {
        "name": "Frost Mirriam",
        "name_zh": "寒霜甘草",
        "img": "jsimgcss\/img\/39.png",
        "code": "00034d32",
        "price": 1,
        "weight": 0.1,
        "store": "不常见",
        "garden": "",
        "e1": "Resist Frost",
        "m1": 1,
        "v1": 1,
        "d1": 1,
        "e2": "Fortify Sneak",
        "m2": 1,
        "v2": 1,
        "d2": 1,
        "e3": "Ravage Magicka",
        "m3": 1,
        "v3": 1,
        "d3": 1,
        "e4": "Damage Stamina Regen",
        "m4": 1,
        "v4": 1,
        "d4": 1
    },
    {
        "name": "Frost Salts",
        "name_zh": "寒霜盐, 霜盐",
        "img": "jsimgcss\/img\/40.png",
        "code": "0003ad5f",
        "price": 100,
        "weight": 0.25,
        "store": "稀有",
        "garden": "",
        "e1": "Weakness to Fire",
        "m1": 1,
        "v1": 1,
        "d1": 1,
        "e2": "Resist Frost",
        "m2": 1,
        "v2": 1,
        "d2": 1,
        "e3": "Restore Magicka",
        "m3": 1,
        "v3": 1,
        "d3": 1,
        "e4": "Fortify Conjuration",
        "m4": 1,
        "v4": 1,
        "d4": 1
    },
    {
        "name": "Garlic",
        "name_zh": "大蒜",
        "img": "jsimgcss\/img\/41.png",
        "code": "00034d22",
        "price": 1,
        "weight": 0.25,
        "store": "常见",
        "garden": "",
        "e1": "Resist Poison",
        "m1": 1,
        "v1": 1,
        "d1": 1,
        "e2": "Fortify Stamina",
        "m2": 1,
        "v2": 1,
        "d2": 1,
        "e3": "Regenerate Magicka",
        "m3": 1,
        "v3": 1,
        "d3": 1,
        "e4": "Regenerate Health",
        "m4": 1,
        "v4": 1,
        "d4": 1
    },
    {
        "name": "Giant Lichen",
        "name_zh": "巨型青苔, 巨型藓",
        "img": "jsimgcss\/img\/42.png",
        "code": "0007e8c1",
        "price": 5,
        "weight": 0.25,
        "store": "不常见",
        "garden": "4",
        "e1": "Weakness to Shock",
        "m1": 1,
        "v1": 1,
        "d1": 1,
        "e2": "Ravage Health",
        "m2": 1,
        "v2": 1,
        "d2": 1,
        "e3": "Weakness to Poison",
        "m3": 1,
        "v3": 1,
        "d3": 1,
        "e4": "Restore Magicka",
        "m4": 1,
        "v4": 1,
        "d4": 1
    },
    {
        "name": "Giant's Toe",
        "name_zh": "巨人脚趾",
        "img": "jsimgcss\/img\/43.png",
        "code": "0003ad64",
        "price": 20,
        "weight": 1,
        "store": "稀有",
        "garden": "",
        "e1": "Damage Stamina",
        "m1": 1,
        "v1": 1,
        "d1": 1,
        "e2": "Fortify Health",
        "m2": 1,
        "v2": 5.9,
        "d2": 5,
        "e3": "Fortify Carry Weight",
        "m3": 1,
        "v3": 1,
        "d3": 1,
        "e4": "Damage Stamina Regen",
        "m4": 1,
        "v4": 1,
        "d4": 1
    },
    {
        "name": "Gleamblossom",
        "name_zh": "幽光萌花\t",
        "img": "jsimgcss\/img\/44.png",
        "code": "xx00b097",
        "price": 5,
        "weight": 0.1,
        "store": "无",
        "garden": "",
        "e1": "Resist Magic",
        "m1": 1,
        "v1": 1,
        "d1": 1,
        "e2": "Fear",
        "m2": 1,
        "v2": 1,
        "d2": 1,
        "e3": "Regenerate Health",
        "m3": 1,
        "v3": 1,
        "d3": 1,
        "e4": "Paralysis",
        "m4": 1,
        "v4": 1,
        "d4": 1
    },
    {
        "name": "Glow Dust",
        "name_zh": "光尘",
        "img": "jsimgcss\/img\/45.png",
        "code": "0003ad73",
        "price": 20,
        "weight": 0.5,
        "store": "不常见",
        "garden": "",
        "e1": "Damage Magicka",
        "m1": 1,
        "v1": 1,
        "d1": 1,
        "e2": "Damage Magicka Regen",
        "m2": 1,
        "v2": 1,
        "d2": 1,
        "e3": "Fortify Destruction",
        "m3": 1,
        "v3": 1,
        "d3": 1,
        "e4": "Resist Shock",
        "m4": 1,
        "v4": 1,
        "d4": 1
    },
    {
        "name": "Glowing Mushroom",
        "name_zh": "微光伞菌, 微光蘑菇",
        "img": "jsimgcss\/img\/46.png",
        "code": "0007ee01",
        "price": 5,
        "weight": 0.2,
        "store": "无",
        "garden": "5",
        "e1": "Resist Shock",
        "m1": 1,
        "v1": 1,
        "d1": 1,
        "e2": "Fortify Destruction",
        "m2": 1,
        "v2": 1,
        "d2": 1,
        "e3": "Fortify Smithing",
        "m3": 1,
        "v3": 1,
        "d3": 1,
        "e4": "Fortify Health",
        "m4": 1,
        "v4": 1,
        "d4": 1
    },
    {
        "name": "Grass Pod",
        "name_zh": "草籽",
        "img": "jsimgcss\/img\/47.png",
        "code": "00083e64",
        "price": 1,
        "weight": 0.1,
        "store": "不常见",
        "garden": "3",
        "e1": "Resist Poison",
        "m1": 1,
        "v1": 1,
        "d1": 1,
        "e2": "Ravage Magicka",
        "m2": 1,
        "v2": 1,
        "d2": 1,
        "e3": "Fortify Alteration",
        "m3": 1,
        "v3": 1,
        "d3": 1,
        "e4": "Restore Magicka",
        "m4": 1,
        "v4": 1,
        "d4": 1
    },
    {
        "name": "Hagraven Claw",
        "name_zh": "乌鸦鬼婆之爪",
        "img": "jsimgcss\/img\/48.png",
        "code": "0006b689",
        "price": 20,
        "weight": 0.25,
        "store": "稀有",
        "garden": "",
        "e1": "Resist Magic",
        "m1": 1,
        "v1": 1,
        "d1": 1,
        "e2": "Lingering Damage Magicka",
        "m2": 1,
        "v2": 1,
        "d2": 1,
        "e3": "Fortify Enchanting",
        "m3": 1,
        "v3": 1,
        "d3": 1,
        "e4": "Fortify Barter",
        "m4": 1,
        "v4": 1,
        "d4": 1
    },
    {
        "name": "Hagraven Feathers",
        "name_zh": "乌鸦鬼婆的羽毛",
        "img": "jsimgcss\/img\/49.png",
        "code": "0003ad66",
        "price": 20,
        "weight": 0.1,
        "store": "稀有",
        "garden": "",
        "e1": "Damage Magicka",
        "m1": 1,
        "v1": 1,
        "d1": 1,
        "e2": "Fortify Conjuration",
        "m2": 1,
        "v2": 1,
        "d2": 1,
        "e3": "Frenzy",
        "m3": 1,
        "v3": 1,
        "d3": 1,
        "e4": "Weakness to Shock",
        "m4": 1,
        "v4": 1,
        "d4": 1
    },
    {
        "name": "Hanging Moss",
        "name_zh": "吊苔",
        "img": "jsimgcss\/img\/50.png",
        "code": "00057f91",
        "price": 1,
        "weight": 0.25,
        "store": "不常见",
        "garden": "",
        "e1": "Damage Magicka",
        "m1": 1,
        "v1": 1,
        "d1": 1,
        "e2": "Fortify Health",
        "m2": 1,
        "v2": 1,
        "d2": 1,
        "e3": "Damage Magicka Regen",
        "m3": 1,
        "v3": 1,
        "d3": 1,
        "e4": "Fortify One-handed",
        "m4": 1,
        "v4": 1,
        "d4": 1
    },
    {
        "name": "Hawk Beak",
        "name_zh": "鹰的喙",
        "img": "jsimgcss\/img\/51.png",
        "code": "000e7ebc",
        "price": 15,
        "weight": 0.25,
        "store": "不常见",
        "garden": "",
        "e1": "Restore Stamina",
        "m1": 1,
        "v1": 1,
        "d1": 1,
        "e2": "Resist Frost",
        "m2": 1,
        "v2": 1,
        "d2": 1,
        "e3": "Fortify Carry Weight",
        "m3": 1,
        "v3": 1,
        "d3": 1,
        "e4": "Resist Shock",
        "m4": 1,
        "v4": 1,
        "d4": 1
    },
    {
        "name": "Hawk Feathers",
        "name_zh": "鹰的羽毛",
        "img": "jsimgcss\/img\/52.png",
        "code": "000e7ed0",
        "price": 15,
        "weight": 0.1,
        "store": "不常见",
        "garden": "",
        "e1": "Cure Disease",
        "m1": 1,
        "v1": 0.36,
        "d1": 1,
        "e2": "Fortify Light Armor",
        "m2": 1,
        "v2": 1,
        "d2": 1,
        "e3": "Fortify One-handed",
        "m3": 1,
        "v3": 1,
        "d3": 1,
        "e4": "Fortify Sneak",
        "m4": 1,
        "v4": 1,
        "d4": 1
    },
    {
        "name": "Hawk's Egg",
        "name_zh": "老鹰蛋",
        "img": "jsimgcss\/img\/53.png",
        "code": "xx00f1cc",
        "price": 5,
        "weight": 0.5,
        "store": "无",
        "garden": "",
        "e1": "Resist Magic",
        "m1": 1,
        "v1": 1,
        "d1": 1,
        "e2": "Damage Magicka Regen",
        "m2": 1,
        "v2": 1,
        "d2": 1,
        "e3": "Waterbreathing",
        "m3": 1,
        "v3": 1,
        "d3": 1,
        "e4": "Lingering Damage Stamina",
        "m4": 1,
        "v4": 1,
        "d4": 1
    },
    {
        "name": "Histcarp",
        "name_zh": "希思特鲤鱼",
        "img": "jsimgcss\/img\/54.png",
        "code": "00106e18",
        "price": 6,
        "weight": 0.25,
        "store": "常见",
        "garden": "",
        "e1": "Restore Stamina",
        "m1": 1,
        "v1": 1,
        "d1": 1,
        "e2": "Fortify Magicka",
        "m2": 1,
        "v2": 1,
        "d2": 1,
        "e3": "Damage Stamina Regen",
        "m3": 1,
        "v3": 1,
        "d3": 1,
        "e4": "Waterbreathing",
        "m4": 1,
        "v4": 1,
        "d4": 1
    },
    {
        "name": "Honeycomb",
        "name_zh": "蜂巢",
        "img": "jsimgcss\/img\/55.png",
        "code": "000b08c5",
        "price": 5,
        "weight": 1,
        "store": "None (Common)",
        "garden": "",
        "e1": "Restore Stamina",
        "m1": 1,
        "v1": 1,
        "d1": 1,
        "e2": "Fortify Block",
        "m2": 0.5,
        "v2": 1,
        "d2": 1,
        "e3": "Fortify Light Armor",
        "m3": 1,
        "v3": 1,
        "d3": 1,
        "e4": "Ravage Stamina",
        "m4": 1,
        "v4": 1,
        "d4": 1
    },
    {
        "name": "Human Flesh",
        "name_zh": "人肉",
        "img": "jsimgcss\/img\/56.png",
        "code": "001016b3",
        "price": 1,
        "weight": 0.25,
        "store": "无",
        "garden": "",
        "e1": "Damage Health",
        "m1": 1,
        "v1": 1,
        "d1": 1,
        "e2": "Paralysis",
        "m2": 1,
        "v2": 1,
        "d2": 1,
        "e3": "Restore Magicka",
        "m3": 1,
        "v3": 1,
        "d3": 1,
        "e4": "Fortify Sneak",
        "m4": 1,
        "v4": 1,
        "d4": 1
    },
    {
        "name": "Human Heart",
        "name_zh": "人类心脏",
        "img": "jsimgcss\/img\/57.png",
        "code": "000b18cd",
        "price": 0,
        "weight": 1,
        "store": "无",
        "garden": "",
        "e1": "Damage Health",
        "m1": 1,
        "v1": 1,
        "d1": 1,
        "e2": "Damage Magicka",
        "m2": 1,
        "v2": 1,
        "d2": 1,
        "e3": "Damage Magicka Regen",
        "m3": 1,
        "v3": 1,
        "d3": 1,
        "e4": "Frenzy",
        "m4": 1,
        "v4": 1,
        "d4": 1
    },
    {
        "name": "Ice Wraith Teeth",
        "name_zh": "冰怨灵的牙, 寒霜幽魂的牙",
        "img": "jsimgcss\/img\/58.png",
        "code": "0003ad6a",
        "price": 30,
        "weight": 0.25,
        "store": "稀有",
        "garden": "",
        "e1": "Weakness to Frost",
        "m1": 1,
        "v1": 1,
        "d1": 1,
        "e2": "Fortify Heavy Armor",
        "m2": 1,
        "v2": 1,
        "d2": 1,
        "e3": "Invisibility",
        "m3": 1,
        "v3": 1,
        "d3": 1,
        "e4": "Weakness to Fire",
        "m4": 1,
        "v4": 1,
        "d4": 1
    },
    {
        "name": "Imp Stool",
        "name_zh": "小恶魔粪, 小恶魔菌",
        "img": "jsimgcss\/img\/59.png",
        "code": "0004da23",
        "price": 0,
        "weight": 0.3,
        "store": "稀有",
        "garden": "4",
        "e1": "Damage Health",
        "m1": 1,
        "v1": 1,
        "d1": 1,
        "e2": "Lingering Damage Health",
        "m2": 1,
        "v2": 1,
        "d2": 1,
        "e3": "Paralysis",
        "m3": 1,
        "v3": 1,
        "d3": 1,
        "e4": "Restore Health",
        "m4": 0.6,
        "v4": 0.57,
        "d4": 1
    },
    {
        "name": "Jazbay Grapes",
        "name_zh": "架子湾葡萄",
        "img": "jsimgcss\/img\/60.png",
        "code": "0006ac4a",
        "price": 1,
        "weight": 0.2,
        "store": "稀有",
        "garden": "3",
        "e1": "Weakness to Magic",
        "m1": 1,
        "v1": 1,
        "d1": 1,
        "e2": "Fortify Magicka",
        "m2": 1,
        "v2": 1,
        "d2": 1,
        "e3": "Regenerate Magicka",
        "m3": 1,
        "v3": 1,
        "d3": 1,
        "e4": "Ravage Health",
        "m4": 1,
        "v4": 1,
        "d4": 1
    },
    {
        "name": "Juniper Berries",
        "name_zh": "刺柏浆果, 茱尼泊尔果",
        "img": "jsimgcss\/img\/61.png",
        "code": "0005076e",
        "price": 1,
        "weight": 0.1,
        "store": "常见",
        "garden": "4",
        "e1": "Weakness to Fire",
        "m1": 1,
        "v1": 1,
        "d1": 1,
        "e2": "Fortify Marksman",
        "m2": 1,
        "v2": 1,
        "d2": 1,
        "e3": "Regenerate Health",
        "m3": 1,
        "v3": 1,
        "d3": 1,
        "e4": "Damage Stamina Regen",
        "m4": 1,
        "v4": 1,
        "d4": 1
    },
    {
        "name": "Large Antlers",
        "name_zh": "长鹿角",
        "img": "jsimgcss\/img\/62.png",
        "code": "0006bc0a",
        "price": 2,
        "weight": 0.1,
        "store": "无",
        "garden": "",
        "e1": "Restore Stamina",
        "m1": 1,
        "v1": 1,
        "d1": 1,
        "e2": "Fortify Stamina",
        "m2": 1,
        "v2": 1,
        "d2": 1,
        "e3": "Slow",
        "m3": 1,
        "v3": 1.75,
        "d3": 6,
        "e4": "Damage Stamina Regen",
        "m4": 1,
        "v4": 1,
        "d4": 1
    },
    {
        "name": "Lavender",
        "name_zh": "薰衣草",
        "img": "jsimgcss\/img\/63.png",
        "code": "00045c28",
        "price": 1,
        "weight": 0.1,
        "store": "常见",
        "garden": "3",
        "e1": "Resist Magic",
        "m1": 1,
        "v1": 1,
        "d1": 1,
        "e2": "Fortify Stamina",
        "m2": 1,
        "v2": 1,
        "d2": 1,
        "e3": "Ravage Magicka",
        "m3": 1,
        "v3": 1,
        "d3": 1,
        "e4": "Fortify Conjuration",
        "m4": 1,
        "v4": 1,
        "d4": 1
    },
    {
        "name": "Luna Moth Wing",
        "name_zh": "月蛾翅膀",
        "img": "jsimgcss\/img\/64.png",
        "code": "000727df",
        "price": 5,
        "weight": 0.1,
        "store": "不常见",
        "garden": "",
        "e1": "Damage Magicka",
        "m1": 1,
        "v1": 1,
        "d1": 1,
        "e2": "Fortify Light Armor",
        "m2": 1,
        "v2": 1,
        "d2": 1,
        "e3": "Regenerate Health",
        "m3": 1,
        "v3": 1,
        "d3": 1,
        "e4": "Invisibility",
        "m4": 1,
        "v4": 1,
        "d4": 1
    },
    {
        "name": "Moon Sugar",
        "name_zh": "月糖, 月亮糖",
        "img": "jsimgcss\/img\/65.png",
        "code": "000d8e3f",
        "price": 50,
        "weight": 0.25,
        "store": "不常见",
        "garden": "",
        "e1": "Weakness to Fire",
        "m1": 1,
        "v1": 1,
        "d1": 1,
        "e2": "Resist Frost",
        "m2": 1,
        "v2": 1,
        "d2": 1,
        "e3": "Restore Magicka",
        "m3": 1,
        "v3": 1,
        "d3": 1,
        "e4": "Regenerate Magicka",
        "m4": 1,
        "v4": 1,
        "d4": 1
    },
    {
        "name": "Mora Tapinella",
        "name_zh": "树伞菌, 天鹅菇",
        "img": "jsimgcss\/img\/66.png",
        "code": "000ec870",
        "price": 4,
        "weight": 0.25,
        "store": "不常见",
        "garden": "3",
        "e1": "Restore Magicka",
        "m1": 1,
        "v1": 1,
        "d1": 1,
        "e2": "Lingering Damage Health",
        "m2": 1,
        "v2": 1,
        "d2": 1,
        "e3": "Regenerate Stamina",
        "m3": 1,
        "v3": 1,
        "d3": 1,
        "e4": "Fortify Illusion",
        "m4": 1,
        "v4": 1,
        "d4": 1
    },
    {
        "name": "Mudcrab Chitin",
        "name_zh": "泥沼蟹壳",
        "img": "jsimgcss\/img\/67.png",
        "code": "0006bc00",
        "price": 2,
        "weight": 0.25,
        "store": "None (Common)",
        "garden": "",
        "e1": "Restore Stamina",
        "m1": 1,
        "v1": 1,
        "d1": 1,
        "e2": "Cure Disease",
        "m2": 1,
        "v2": 1,
        "d2": 1,
        "e3": "Resist Poison",
        "m3": 1,
        "v3": 1,
        "d3": 1,
        "e4": "Resist Fire",
        "m4": 1,
        "v4": 1,
        "d4": 1
    },
    {
        "name": "Namira's Rot",
        "name_zh": "娜米拉腐菌, 娜米拉的腐坏物",
        "img": "jsimgcss\/img\/68.png",
        "code": "0004da24",
        "price": 0,
        "weight": 0.25,
        "store": "不常见",
        "garden": "3",
        "e1": "Damage Magicka",
        "m1": 1,
        "v1": 1,
        "d1": 1,
        "e2": "Fortify Lockpicking",
        "m2": 1,
        "v2": 1,
        "d2": 1,
        "e3": "Fear",
        "m3": 1,
        "v3": 1,
        "d3": 1,
        "e4": "Regenerate Health",
        "m4": 1,
        "v4": 1,
        "d4": 1
    },
    {
        "name": "Netch Jelly",
        "name_zh": "气母胶质",
        "img": "jsimgcss\/img\/69.png",
        "code": "xx01cd72",
        "price": 20,
        "weight": 0.5,
        "store": "",
        "garden": "",
        "e1": "Paralysis",
        "m1": 1,
        "v1": 1,
        "d1": 1,
        "e2": "Fortify Carry Weight",
        "m2": 1,
        "v2": 1,
        "d2": 1,
        "e3": "Restore Stamina",
        "m3": 2,
        "v3": 1,
        "d3": 1,
        "e4": "Fear",
        "m4": 1,
        "v4": 1,
        "d4": 1
    },
    {
        "name": "Nightshade",
        "name_zh": "龙葵, 夜茄",
        "img": "jsimgcss\/img\/70.png",
        "code": "0002f44c",
        "price": 8,
        "weight": 0.1,
        "store": "稀有",
        "garden": "3",
        "e1": "Damage Health",
        "m1": 1,
        "v1": 1,
        "d1": 1,
        "e2": "Damage Magicka Regen",
        "m2": 1,
        "v2": 1,
        "d2": 1,
        "e3": "Lingering Damage Stamina",
        "m3": 1,
        "v3": 1,
        "d3": 1,
        "e4": "Fortify Destruction",
        "m4": 0.8,
        "v4": 1,
        "d4": 1
    },
    {
        "name": "Nirnroot",
        "name_zh": "奈恩根",
        "img": "jsimgcss\/img\/71.png",
        "code": "00059b86",
        "price": 10,
        "weight": 0.2,
        "store": "稀有",
        "garden": "",
        "e1": "Damage Health",
        "m1": 1,
        "v1": 12.6,
        "d1": 1,
        "e2": "Damage Stamina",
        "m2": 1,
        "v2": 1,
        "d2": 1,
        "e3": "Invisibility",
        "m3": 1,
        "v3": 1,
        "d3": 1,
        "e4": "Resist Magic",
        "m4": 1,
        "v4": 1,
        "d4": 1
    },
    {
        "name": "Nordic Barnacle",
        "name_zh": "诺德藤壶",
        "img": "jsimgcss\/img\/72.png",
        "code": "0007edf5",
        "price": 5,
        "weight": 0.2,
        "store": "不常见",
        "garden": "",
        "e1": "Damage Magicka",
        "m1": 1,
        "v1": 1,
        "d1": 1,
        "e2": "Waterbreathing",
        "m2": 1,
        "v2": 1,
        "d2": 1,
        "e3": "Regenerate Health",
        "m3": 1,
        "v3": 1,
        "d3": 1,
        "e4": "Fortify Pickpocket",
        "m4": 1,
        "v4": 1,
        "d4": 1
    },
    {
        "name": "Orange Dartwing",
        "name_zh": "橙色飞虫, 橙色飞翼",
        "img": "jsimgcss\/img\/73.png",
        "code": "000bb956",
        "price": 1,
        "weight": 0.1,
        "store": "无",
        "garden": "",
        "e1": "Restore Stamina",
        "m1": 1,
        "v1": 1,
        "d1": 1,
        "e2": "Ravage Magicka",
        "m2": 1,
        "v2": 1,
        "d2": 1,
        "e3": "Fortify Pickpocket",
        "m3": 1,
        "v3": 1,
        "d3": 1,
        "e4": "Lingering Damage Health",
        "m4": 1,
        "v4": 1,
        "d4": 1
    },
    {
        "name": "Pearl",
        "name_zh": "珍珠",
        "img": "jsimgcss\/img\/74.png",
        "code": "000854fe",
        "price": 2,
        "weight": 0.1,
        "store": "None (Rare)",
        "garden": "",
        "e1": "Restore Stamina",
        "m1": 1,
        "v1": 1,
        "d1": 1,
        "e2": "Fortify Block",
        "m2": 1,
        "v2": 1,
        "d2": 1,
        "e3": "Restore Magicka",
        "m3": 1,
        "v3": 1,
        "d3": 1,
        "e4": "Resist Shock",
        "m4": 1,
        "v4": 1,
        "d4": 1
    },
    {
        "name": "Pine Thrush Egg",
        "name_zh": "松木画眉蛋, 松雀卵",
        "img": "jsimgcss\/img\/75.png",
        "code": "00023d6f",
        "price": 2,
        "weight": 0.5,
        "store": "常见",
        "garden": "",
        "e1": "Restore Stamina",
        "m1": 1,
        "v1": 1,
        "d1": 1,
        "e2": "Fortify Lockpicking",
        "m2": 1,
        "v2": 1,
        "d2": 1,
        "e3": "Weakness to Poison",
        "m3": 1,
        "v3": 1,
        "d3": 1,
        "e4": "Resist Shock",
        "m4": 1,
        "v4": 1,
        "d4": 1
    },
    {
        "name": "Poison Bloom",
        "name_zh": "毒茂花",
        "img": "jsimgcss\/img\/76.png",
        "code": "xx0185fb",
        "price": 5,
        "weight": 0.25,
        "store": "无",
        "garden": "",
        "e1": "Damage Health",
        "m1": 1.5,
        "v1": 1,
        "d1": 1,
        "e2": "Slow",
        "m2": 1,
        "v2": 1,
        "d2": 1,
        "e3": "Fortify Carry Weight",
        "m3": 1,
        "v3": 1,
        "d3": 1,
        "e4": "Fear",
        "m4": 1,
        "v4": 1,
        "d4": 1
    },
    {
        "name": "Powdered Mammoth Tusk",
        "name_zh": "长毛象牙粉, 猛犸象牙粉",
        "img": "jsimgcss\/img\/77.png",
        "code": "0006bc10",
        "price": 2,
        "weight": 0.1,
        "store": "无",
        "garden": "",
        "e1": "Restore Stamina",
        "m1": 1,
        "v1": 1,
        "d1": 1,
        "e2": "Fortify Sneak",
        "m2": 1,
        "v2": 1,
        "d2": 1,
        "e3": "Weakness to Fire",
        "m3": 1,
        "v3": 1,
        "d3": 1,
        "e4": "Fear",
        "m4": 1,
        "v4": 1,
        "d4": 1
    },
    {
        "name": "Purple Mountain Flower",
        "name_zh": "紫山花",
        "img": "jsimgcss\/img\/78.png",
        "code": "00077e1e",
        "price": 2,
        "weight": 0.1,
        "store": "常见",
        "garden": "3",
        "e1": "Restore Stamina",
        "m1": 1,
        "v1": 1,
        "d1": 1,
        "e2": "Fortify Sneak",
        "m2": 1,
        "v2": 1,
        "d2": 1,
        "e3": "Lingering Damage Magicka",
        "m3": 1,
        "v3": 1,
        "d3": 1,
        "e4": "Resist Frost",
        "m4": 1,
        "v4": 1,
        "d4": 1
    },
    {
        "name": "Red Mountain Flower",
        "name_zh": "红山花",
        "img": "jsimgcss\/img\/79.png",
        "code": "00077e1d",
        "price": 2,
        "weight": 0.1,
        "store": "常见",
        "garden": "3",
        "e1": "Restore Magicka",
        "m1": 1,
        "v1": 1,
        "d1": 1,
        "e2": "Ravage Magicka",
        "m2": 1,
        "v2": 1,
        "d2": 1,
        "e3": "Fortify Magicka",
        "m3": 1,
        "v3": 1,
        "d3": 1,
        "e4": "Damage Health",
        "m4": 1,
        "v4": 1,
        "d4": 1
    },
    {
        "name": "River Betty",
        "name_zh": "河布丁",
        "img": "jsimgcss\/img\/80.png",
        "code": "00106e1a",
        "price": 15,
        "weight": 0.25,
        "store": "常见",
        "garden": "",
        "e1": "Damage Health",
        "m1": 2.5,
        "v1": 1,
        "d1": 1,
        "e2": "Fortify Alteration",
        "m2": 1,
        "v2": 1,
        "d2": 1,
        "e3": "Slow",
        "m3": 1,
        "v3": 1,
        "d3": 1,
        "e4": "Fortify Carry Weight",
        "m4": 1,
        "v4": 1,
        "d4": 1
    },
    {
        "name": "Rock Warbler Egg",
        "name_zh": "石栖刺莺的蛋, 石栖刺莺卵",
        "img": "jsimgcss\/img\/81.png",
        "code": "0007e8c8",
        "price": 2,
        "weight": 0.5,
        "store": "不常见",
        "garden": "",
        "e1": "Restore Health",
        "m1": 1,
        "v1": 1,
        "d1": 1,
        "e2": "Fortify One-handed",
        "m2": 1,
        "v2": 1,
        "d2": 1,
        "e3": "Damage Stamina",
        "m3": 1,
        "v3": 1,
        "d3": 1,
        "e4": "Weakness to Magic",
        "m4": 1,
        "v4": 1,
        "d4": 1
    },
    {
        "name": "Sabre Cat Tooth",
        "name_zh": "剑齿虎牙齿",
        "img": "jsimgcss\/img\/82.png",
        "code": "0006bc04",
        "price": 2,
        "weight": 0.1,
        "store": "无",
        "garden": "",
        "e1": "Restore Stamina",
        "m1": 1,
        "v1": 1,
        "d1": 1,
        "e2": "Fortify Heavy Armor",
        "m2": 1,
        "v2": 1,
        "d2": 1,
        "e3": "Fortify Smithing",
        "m3": 1,
        "v3": 1,
        "d3": 1,
        "e4": "Weakness to Poison",
        "m4": 1,
        "v4": 1,
        "d4": 1
    },
    {
        "name": "Salmon Roe",
        "name_zh": "鲑鱼鱼卵",
        "img": "jsimgcss\/img\/83.png",
        "code": "xx003545",
        "price": 5,
        "weight": 0.2,
        "store": "无",
        "garden": "",
        "e1": "Restore Stamina",
        "m1": 0.4,
        "v1": 0.36,
        "d1": 1,
        "e2": "Waterbreathing",
        "m2": 1,
        "v2": 15.4,
        "d2": 12,
        "e3": "Fortify Magicka",
        "m3": 12.5,
        "v3": 1.05,
        "d3": 0.08,
        "e4": "Regenerate Magicka",
        "m4": 1,
        "v4": 1,
        "d4": 1
    },
    {
        "name": "Salt Pile",
        "name_zh": "盐堆, 盐",
        "img": "jsimgcss\/img\/84.png",
        "code": "00034cdf",
        "price": 2,
        "weight": 0.2,
        "store": "常见",
        "garden": "",
        "e1": "Weakness to Magic",
        "m1": 1,
        "v1": 1,
        "d1": 1,
        "e2": "Fortify Restoration",
        "m2": 1,
        "v2": 1,
        "d2": 1,
        "e3": "Slow",
        "m3": 1,
        "v3": 1,
        "d3": 1,
        "e4": "Regenerate Magicka",
        "m4": 1,
        "v4": 1,
        "d4": 1
    },
    {
        "name": "Scaly Pholiota",
        "name_zh": "鳞片伞菌, 鳞片菇",
        "img": "jsimgcss\/img\/85.png",
        "code": "0006f950",
        "price": 4,
        "weight": 0.25,
        "store": "不常见",
        "garden": "5",
        "e1": "Weakness to Magic",
        "m1": 1,
        "v1": 1,
        "d1": 1,
        "e2": "Fortify Illusion",
        "m2": 1,
        "v2": 1,
        "d2": 1,
        "e3": "Regenerate Stamina",
        "m3": 1,
        "v3": 1,
        "d3": 1,
        "e4": "Fortify Carry Weight",
        "m4": 1,
        "v4": 1,
        "d4": 1
    },
    {
        "name": "Scathecraw",
        "name_zh": "苦痛草",
        "img": "jsimgcss\/img\/86.png",
        "code": "xx017e97",
        "price": 1,
        "weight": 0.1,
        "store": "",
        "garden": "",
        "e1": "Ravage Health",
        "m1": 1,
        "v1": 1,
        "d1": 1,
        "e2": "Ravage Stamina",
        "m2": 1,
        "v2": 1,
        "d2": 1,
        "e3": "Ravage Magicka",
        "m3": 1,
        "v3": 1,
        "d3": 1,
        "e4": "Lingering Damage Health",
        "m4": 1,
        "v4": 1,
        "d4": 1
    },
    {
        "name": "Silverside Perch",
        "name_zh": "银岸鲈鱼",
        "img": "jsimgcss\/img\/87.png",
        "code": "00106e1c",
        "price": 15,
        "weight": 0.25,
        "store": "常见",
        "garden": "",
        "e1": "Restore Stamina",
        "m1": 1,
        "v1": 1,
        "d1": 1,
        "e2": "Damage Stamina Regen",
        "m2": 1,
        "v2": 1,
        "d2": 1,
        "e3": "Ravage Health",
        "m3": 1,
        "v3": 1,
        "d3": 1,
        "e4": "Resist Frost",
        "m4": 1,
        "v4": 1,
        "d4": 1
    },
    {
        "name": "Skeever Tail",
        "name_zh": "恶鼠尾巴, 雪鼠尾巴",
        "img": "jsimgcss\/img\/88.png",
        "code": "0003ad6f",
        "price": 3,
        "weight": 0.2,
        "store": "常见",
        "garden": "",
        "e1": "Damage Stamina Regen",
        "m1": 1,
        "v1": 1,
        "d1": 1,
        "e2": "Ravage Health",
        "m2": 1,
        "v2": 1,
        "d2": 1,
        "e3": "Damage Health",
        "m3": 1,
        "v3": 1,
        "d3": 1,
        "e4": "Fortify Light Armor",
        "m4": 1,
        "v4": 1,
        "d4": 1
    },
    {
        "name": "Slaughterfish Egg",
        "name_zh": "食人鱼卵",
        "img": "jsimgcss\/img\/89.png",
        "code": "0007e8c5",
        "price": 3,
        "weight": 0.2,
        "store": "不常见",
        "garden": "",
        "e1": "Resist Poison",
        "m1": 1,
        "v1": 1,
        "d1": 1,
        "e2": "Fortify Pickpocket",
        "m2": 1,
        "v2": 1,
        "d2": 1,
        "e3": "Lingering Damage Health",
        "m3": 1,
        "v3": 1,
        "d3": 1,
        "e4": "Fortify Stamina",
        "m4": 1,
        "v4": 1,
        "d4": 1
    },
    {
        "name": "Slaughterfish Scales",
        "name_zh": "食人鱼鳞",
        "img": "jsimgcss\/img\/90.png",
        "code": "0003ad70",
        "price": 3,
        "weight": 0.1,
        "store": "不常见",
        "garden": "",
        "e1": "Resist Frost",
        "m1": 1,
        "v1": 1,
        "d1": 1,
        "e2": "Lingering Damage Health",
        "m2": 1,
        "v2": 1,
        "d2": 1,
        "e3": "Fortify Heavy Armor",
        "m3": 1,
        "v3": 1,
        "d3": 1,
        "e4": "Fortify Block",
        "m4": 1,
        "v4": 1,
        "d4": 1
    },
    {
        "name": "Small Antlers",
        "name_zh": "短鹿角",
        "img": "jsimgcss\/img\/91.png",
        "code": "0006bc0b",
        "price": 2,
        "weight": 0.1,
        "store": "None (Common)",
        "garden": "",
        "e1": "Weakness to Poison",
        "m1": 1,
        "v1": 1,
        "d1": 1,
        "e2": "Fortify Restoration",
        "m2": 1,
        "v2": 1,
        "d2": 1,
        "e3": "Lingering Damage Stamina",
        "m3": 1,
        "v3": 1,
        "d3": 1,
        "e4": "Damage Health",
        "m4": 1,
        "v4": 1,
        "d4": 1
    },
    {
        "name": "Small Pearl",
        "name_zh": "小珍珠",
        "img": "jsimgcss\/img\/92.png",
        "code": "00085500",
        "price": 2,
        "weight": 0.1,
        "store": "无",
        "garden": "",
        "e1": "Restore Stamina",
        "m1": 1,
        "v1": 1,
        "d1": 1,
        "e2": "Fortify One-handed",
        "m2": 1,
        "v2": 1,
        "d2": 1,
        "e3": "Fortify Restoration",
        "m3": 1,
        "v3": 1,
        "d3": 1,
        "e4": "Resist Frost",
        "m4": 1,
        "v4": 1,
        "d4": 1
    },
    {
        "name": "Snowberries",
        "name_zh": "雪浆果",
        "img": "jsimgcss\/img\/93.png",
        "code": "0001b3bd",
        "price": 4,
        "weight": 0.1,
        "store": "常见",
        "garden": "4",
        "e1": "Resist Fire",
        "m1": 1,
        "v1": 1,
        "d1": 1,
        "e2": "Fortify Enchanting",
        "m2": 1,
        "v2": 1,
        "d2": 1,
        "e3": "Resist Frost",
        "m3": 1,
        "v3": 1,
        "d3": 1,
        "e4": "Resist Shock",
        "m4": 1,
        "v4": 1,
        "d4": 1
    },
    {
        "name": "Spawn Ash",
        "name_zh": "灰烬魔尘,凝灰鬼尘",
        "img": "jsimgcss\/img\/94.png",
        "code": "xx01cd6d",
        "price": 20,
        "weight": 0.1,
        "store": "",
        "garden": "",
        "e1": "Ravage Stamina",
        "m1": 1,
        "v1": 1,
        "d1": 1,
        "e2": "Resist Fire",
        "m2": 1,
        "v2": 1,
        "d2": 1,
        "e3": "Fortify Enchanting",
        "m3": 1,
        "v3": 1,
        "d3": 1,
        "e4": "Ravage Magicka",
        "m4": 1,
        "v4": 1,
        "d4": 1
    },
    {
        "name": "Spider Egg",
        "name_zh": "蜘蛛卵",
        "img": "jsimgcss\/img\/95.png",
        "code": "0009151b",
        "price": 5,
        "weight": 0.2,
        "store": "不常见",
        "garden": "",
        "e1": "Damage Stamina",
        "m1": 1,
        "v1": 1,
        "d1": 1,
        "e2": "Damage Magicka Regen",
        "m2": 1,
        "v2": 1,
        "d2": 1,
        "e3": "Fortify Lockpicking",
        "m3": 1,
        "v3": 1,
        "d3": 1,
        "e4": "Fortify Marksman",
        "m4": 1,
        "v4": 1,
        "d4": 1
    },
    {
        "name": "Spriggan Sap",
        "name_zh": "树精的树液",
        "img": "jsimgcss\/img\/96.png",
        "code": "00063b5f",
        "price": 15,
        "weight": 0.2,
        "store": "不常见",
        "garden": "",
        "e1": "Damage Magicka Regen",
        "m1": 1,
        "v1": 1,
        "d1": 1,
        "e2": "Fortify Enchanting",
        "m2": 1,
        "v2": 1,
        "d2": 1,
        "e3": "Fortify Smithing",
        "m3": 1,
        "v3": 1,
        "d3": 1,
        "e4": "Fortify Alteration",
        "m4": 1,
        "v4": 1,
        "d4": 1
    },
    {
        "name": "Swamp Fungal Pod",
        "name_zh": "沼泽真菌荚",
        "img": "jsimgcss\/img\/97.png",
        "code": "0007e8b7",
        "price": 5,
        "weight": 0.25,
        "store": "不常见",
        "garden": "3",
        "e1": "Resist Shock",
        "m1": 1,
        "v1": 1,
        "d1": 1,
        "e2": "Lingering Damage Magicka",
        "m2": 1,
        "v2": 1,
        "d2": 1,
        "e3": "Paralysis",
        "m3": 1,
        "v3": 1,
        "d3": 1,
        "e4": "Restore Health",
        "m4": 1,
        "v4": 1,
        "d4": 1
    },
    {
        "name": "Taproot",
        "name_zh": "直立根",
        "img": "jsimgcss\/img\/98.png",
        "code": "0003ad71",
        "price": 15,
        "weight": 0.5,
        "store": "不常见",
        "garden": "",
        "e1": "Weakness to Magic",
        "m1": 1,
        "v1": 1,
        "d1": 1,
        "e2": "Fortify Illusion",
        "m2": 1,
        "v2": 1,
        "d2": 1,
        "e3": "Regenerate Magicka",
        "m3": 1,
        "v3": 1,
        "d3": 1,
        "e4": "Restore Magicka",
        "m4": 1,
        "v4": 1,
        "d4": 1
    },
    {
        "name": "Thistle Branch",
        "name_zh": "蓟丛,蓟花",
        "img": "jsimgcss\/img\/99.png",
        "code": "000134aa",
        "price": 1,
        "weight": 0.1,
        "store": "常见",
        "garden": "3",
        "e1": "Resist Frost",
        "m1": 1,
        "v1": 1,
        "d1": 1,
        "e2": "Ravage Stamina",
        "m2": 1,
        "v2": 1,
        "d2": 1,
        "e3": "Resist Poison",
        "m3": 0.75,
        "v3": 0.1,
        "d3": 0,
        "e4": "Fortify Heavy Armor",
        "m4": 1,
        "v4": 1,
        "d4": 1
    },
    {
        "name": "Torchbug Thorax",
        "name_zh": "萤火虫的胸壳",
        "img": "jsimgcss\/img\/100.png",
        "code": "0004da73",
        "price": 1,
        "weight": 0.1,
        "store": "无",
        "garden": "",
        "e1": "Restore Stamina",
        "m1": 1,
        "v1": 1,
        "d1": 1,
        "e2": "Lingering Damage Magicka",
        "m2": 1,
        "v2": 1,
        "d2": 1,
        "e3": "Weakness to Magic",
        "m3": 1,
        "v3": 1,
        "d3": 1,
        "e4": "Fortify Stamina",
        "m4": 1,
        "v4": 1,
        "d4": 1
    },
    {
        "name": "Trama Root",
        "name_zh": "特拉玛根",
        "img": "jsimgcss\/img\/101.png",
        "code": "xx017008",
        "price": 1,
        "weight": 0.2,
        "store": "",
        "garden": "",
        "e1": "Weakness to Shock",
        "m1": 1,
        "v1": 1,
        "d1": 1,
        "e2": "Fortify Carry Weight",
        "m2": 1,
        "v2": 1,
        "d2": 1,
        "e3": "Damage Magicka",
        "m3": 1,
        "v3": 1,
        "d3": 1,
        "e4": "Slow",
        "m4": 1,
        "v4": 1,
        "d4": 1
    },
    {
        "name": "Troll Fat",
        "name_zh": "巨魔脂肪",
        "img": "jsimgcss\/img\/102.png",
        "code": "0003ad72",
        "price": 15,
        "weight": 1,
        "store": "不常见",
        "garden": "",
        "e1": "Resist Poison",
        "m1": 1,
        "v1": 1,
        "d1": 1,
        "e2": "Fortify Two-handed",
        "m2": 1,
        "v2": 1,
        "d2": 1,
        "e3": "Frenzy",
        "m3": 1,
        "v3": 1,
        "d3": 1,
        "e4": "Damage Health",
        "m4": 1,
        "v4": 1,
        "d4": 1
    },
    {
        "name": "Tundra Cotton",
        "name_zh": "苔原棉花",
        "img": "jsimgcss\/img\/103.png",
        "code": "0003f7f8",
        "price": 1,
        "weight": 0.1,
        "store": "常见",
        "garden": "3",
        "e1": "Resist Magic",
        "m1": 1,
        "v1": 1,
        "d1": 1,
        "e2": "Fortify Magicka",
        "m2": 1,
        "v2": 1,
        "d2": 1,
        "e3": "Fortify Block",
        "m3": 1,
        "v3": 1,
        "d3": 1,
        "e4": "Fortify Barter",
        "m4": 1,
        "v4": 1,
        "d4": 1
    },
    {
        "name": "Vampire Dust",
        "name_zh": "吸血鬼灰烬",
        "img": "jsimgcss\/img\/104.png",
        "code": "0003ad76",
        "price": 25,
        "weight": 0.2,
        "store": "稀有",
        "garden": "",
        "e1": "Invisibility",
        "m1": 1,
        "v1": 1,
        "d1": 1,
        "e2": "Restore Magicka",
        "m2": 1,
        "v2": 1,
        "d2": 1,
        "e3": "Regenerate Health",
        "m3": 1,
        "v3": 1,
        "d3": 1,
        "e4": "Cure Disease",
        "m4": 1,
        "v4": 1,
        "d4": 1
    },
    {
        "name": "Void Salts",
        "name_zh": "虚无盐",
        "img": "jsimgcss\/img\/105.png",
        "code": "0003ad60",
        "price": 125,
        "weight": 0.2,
        "store": "稀有",
        "garden": "",
        "e1": "Weakness to Shock",
        "m1": 1,
        "v1": 1,
        "d1": 1,
        "e2": "Resist Magic",
        "m2": 1,
        "v2": 1,
        "d2": 1,
        "e3": "Damage Health",
        "m3": 1,
        "v3": 1,
        "d3": 1,
        "e4": "Fortify Magicka",
        "m4": 1,
        "v4": 1,
        "d4": 1
    },
    {
        "name": "Wheat",
        "name_zh": "小麦",
        "img": "jsimgcss\/img\/106.png",
        "code": "0004b0ba",
        "price": 5,
        "weight": 0.1,
        "store": "常见",
        "garden": "4",
        "e1": "Restore Health",
        "m1": 1,
        "v1": 1,
        "d1": 1,
        "e2": "Fortify Health",
        "m2": 1,
        "v2": 1,
        "d2": 1,
        "e3": "Damage Stamina Regen",
        "m3": 1,
        "v3": 1,
        "d3": 1,
        "e4": "Lingering Damage Magicka",
        "m4": 1,
        "v4": 1,
        "d4": 1
    },
    {
        "name": "White Cap",
        "name_zh": "白帽伞菌, 白帽子",
        "img": "jsimgcss\/img\/107.png",
        "code": "0004da22",
        "price": 0,
        "weight": 0.3,
        "store": "不常见",
        "garden": "2",
        "e1": "Weakness to Frost",
        "m1": 1,
        "v1": 1,
        "d1": 1,
        "e2": "Fortify Heavy Armor",
        "m2": 1,
        "v2": 1,
        "d2": 1,
        "e3": "Restore Magicka",
        "m3": 1,
        "v3": 1,
        "d3": 1,
        "e4": "Ravage Magicka",
        "m4": 1,
        "v4": 1,
        "d4": 1
    },
    {
        "name": "Wisp Wrappings",
        "name_zh": "幽魂外皮",
        "img": "jsimgcss\/img\/108.png",
        "code": "0006bc0e",
        "price": 2,
        "weight": 0.1,
        "store": "无",
        "garden": "",
        "e1": "Restore Stamina",
        "m1": 1,
        "v1": 1,
        "d1": 1,
        "e2": "Fortify Destruction",
        "m2": 1,
        "v2": 1,
        "d2": 1,
        "e3": "Fortify Carry Weight",
        "m3": 1,
        "v3": 1,
        "d3": 1,
        "e4": "Resist Magic",
        "m4": 1,
        "v4": 1,
        "d4": 1
    },
    {
        "name": "Yellow Mountain Flower",
        "name_zh": "黄色山花,黄山花",
        "img": "jsimgcss\/img\/109.png",
        "code": "xx002a78",
        "price": 2,
        "weight": 0.1,
        "store": "无",
        "garden": "",
        "e1": "Resist Poison",
        "m1": 1,
        "v1": 1,
        "d1": 1,
        "e2": "Fortify Restoration",
        "m2": 1.25,
        "v2": 1,
        "d2": 1,
        "e3": "Fortify Health",
        "m3": 1,
        "v3": 1,
        "d3": 1,
        "e4": "Damage Stamina Regen",
        "m4": 1,
        "v4": 1,
        "d4": 1
    }
];
//数字表示当前效果的满级价格
var G_Effect = {
    'Damage Health': {price: 3, zh1: '伤害生命', zh: '伤害生命(Damage Health):涂抹在武器上，给敌人造成直接的生命伤害。'},
    'Damage Magicka': {price: 52, zh1: '伤害法力', zh: '伤害法力(Damage Magicka) : 涂抹在武器上，给敌人造成直接的法力伤害。'},
    'Damage Stamina': {price: 43, zh1: '伤害耐力', zh: '伤害耐力(Damage Stamina) : 涂抹在武器上，给敌人造成直接的耐力/精力伤害。'},
    'Lingering Damage Health': {price: 86, zh1: '持续伤害生命', zh: '持续伤害生命(Lingering Damage Health) : 涂抹在武器上，给敌人造成持续的生命伤害。'},
    'Lingering Damage Magicka': {
        price: 71,
        zh1: '持续伤害法力',
        zh: '持续伤害法力(Lingering Damage Magicka) : 涂抹在武器上，给敌人造成持续的法力伤害。'
    },
    'Lingering Damage Stamina': {
        price: 12,
        zh1: '持续伤害耐力',
        zh: '持续伤害耐力(Lingering Damage Stamina) : 涂抹在武器上，给敌人造成持续的耐力/精力伤害。'
    },
    'Damage Magicka Regen': {price: 265, zh1: '减慢法力回复', zh: '减慢法力回复(Damage Magicka Regen) : 涂抹在武器上，减缓敌人法力回复速度。'},
    'Damage Stamina Regen': {price: 159, zh1: '减慢耐力回复', zh: '减慢耐力回复(Damage Stamina Regen) : 涂抹在武器上，减缓敌人耐力/精力回复速度。'},
    'Ravage Health': {
        price: 6,
        zh1: '破坏生命+',
        zh: '破坏生命+(Ravage Health) : 涂抹在武器上，给敌人造成直接的生命伤害，并降低敌人生命最大值（在一定时间内阻止敌人回复生命）（存疑）。'
    },
    'Ravage Magicka': {
        price: 15,
        zh1: '破坏法力+',
        zh: '破坏法力+(Ravage Magicka) : 涂抹在武器上，给敌人造成直接的法力伤害，并降低敌人法力最大值（在一定时间内阻止敌人回复法力）（存疑）。'
    },
    'Ravage Stamina': {
        price: 24,
        zh1: '破坏耐力+',
        zh: '破坏耐力+(Ravage Stamina) : 涂抹在武器上，给敌人造成直接的耐力/精力伤害，并降低敌人耐力/精力最大值（在一定时间内阻止敌人回复耐力/精力）（存疑）。'
    },
    'Weakness to Fire': {price: 48, zh1: '破坏火抗', zh: '破坏火抗(Weakness to Fire) : 涂抹在武器上，降低敌人的火焰属性攻击抗性。'},
    'Weakness to Frost': {price: 40, zh1: '破坏冰抗', zh: '破坏冰抗(Weakness to Frost) : 涂抹在武器上，降低敌人的寒冰属性攻击抗性。'},
    'Weakness to Magic': {price: 51, zh1: '破坏魔抗', zh: '破坏魔抗(Weakness to Magic) : 涂抹在武器上，降低敌人的魔法属性攻击抗性。'},
    'Weakness to Poison': {price: 51, zh1: '破坏毒抗', zh: '破坏毒抗(Weakness to Poison) : 涂抹在武器上，降低敌人的剧毒属性攻击抗性。'},
    'Weakness to Shock': {price: 56, zh1: '破坏电抗', zh: '破坏电抗(Weakness to Shock) : 涂抹在武器上，降低敌人的闪电属性攻击抗性。'},
    'Fear': {price: 120, zh1: '恐惧术', zh: '恐惧术(Fear) : 涂抹在武器上，让武器附带恐惧术效果，持续一段时间。'},
    'Frenzy': {price: 107, zh1: '狂暴术', zh: '狂暴术(Frenzy) : 涂抹在武器上，让武器附带狂暴术效果，持续一段时间。'},
    'Slow': {price: 247, zh1: '迟缓术', zh: '迟缓术(Slow) : 涂抹在武器上，让武器附带迟缓术效果，持续一段时间。'},
    'Paralysis': {price: 285, zh1: '麻痹术', zh: '麻痹术(Paralysis) : 涂抹在武器上，让武器附带麻痹术效果(有概率晕倒)，持续一段时间。'},

    'Restore Health': {price: 21, zh1: '回复生命', zh: '回复生命(Restore Health) : 立即回复自身的生命值。'},
    'Restore Magicka': {price: 25, zh1: '回复法力', zh: '回复法力(Restore Magicka) : 立即回复自身的法力值。'},
    'Restore Stamina': {price: 25, zh1: '回复耐力', zh: '回复耐力(Restore Stamina) : 立即回复自身的耐力/精力值。'},
    'Fortify Health': {price: 82, zh1: '增加生命上限', zh: '增加生命上限(Fortify Health) : 增加自身的生命值上限，持续一段时间。'},
    'Fortify Magicka': {price: 71, zh1: '增加法力上限', zh: '增加法力上限(Fortify Magicka) : 增加自身的法力值上限，持续一段时间。'},
    'Fortify Stamina': {price: 71, zh1: '增加耐力上限', zh: '增加耐力上限(Fortify Stamina) : 增加自身的耐力/精力值上限，持续一段时间。'},
    'Regenerate Health': {price: 177, zh1: '加快生命回复', zh: '加快生命回复(Regenerate Health) : 增加自身的生命值回复速度，持续一段时间。'},
    'Regenerate Magicka': {price: 177, zh1: '加快法力回复', zh: '加快法力回复(Regenerate Magicka) : 增加自身的法力值回复速度，持续一段时间。'},
    'Regenerate Stamina': {price: 177, zh1: '加快耐力回复', zh: '加快耐力回复(Regenerate Stamina) : 增加自身的耐力/精力值回复速度，持续一段时间。'},
    'Resist Fire': {price: 86, zh1: '强化火抗', zh: '强化火抗(Resist Fire) : 增强自身的火焰属性攻击抗性，持续一段时间。'},
    'Resist Frost': {price: 86, zh1: '强化冰抗', zh: '强化冰抗(Resist Frost) : 增强自身的寒冰属性攻击抗性，持续一段时间。'},
    'Resist Magic': {price: 51, zh1: '强化魔抗', zh: '强化魔抗(Resist Magic) : 增强自身的魔法属性攻击抗性，持续一段时间。'},
    'Resist Poison': {price: 118, zh1: '强化毒抗', zh: '强化毒抗(Resist Poison) : 增强自身的剧毒属性攻击抗性，持续一段时间。'},
    'Resist Shock': {price: 86, zh1: '强化电抗', zh: '强化电抗(Resist Shock) : 增强自身的闪电属性攻击抗性，持续一段时间。'},
    'Fortify Alteration': {price: 47, zh1: '强化变化魔法', zh: '强化变化魔法(Fortify Alteration) : 增强自身的变化系魔法威力，持续一段时间。'},
    'Fortify Conjuration': {price: 75, zh1: '强化召唤魔法', zh: '强化召唤魔法(Fortify Conjuration) : 增强自身的召唤系魔法威力，持续一段时间。'},
    'Fortify Destruction': {price: 151, zh1: '强化毁灭魔法', zh: '强化毁灭魔法(Fortify Destruction) : 增强自身的毁灭系魔法威力，持续一段时间。'},
    'Fortify Illusion': {price: 94, zh1: '强化幻术魔法', zh: '强化幻术魔法(Fortify Illusion) : 增强自身的幻术系魔法威力，持续一段时间。'},
    'Fortify Restoration': {price: 118, zh1: '强化恢复魔法', zh: '强化恢复魔法(Fortify Restoration) : 增强自身的恢复系魔法威力，持续一段时间。'},
    'Fortify Marksman': {price: 118, zh1: '强化箭术', zh: '强化箭术(Fortify Marksman) : 增强自身弓箭的威力，持续一段时间。'},
    'Fortify Two-handed': {price: 118, zh1: '强化双手武器', zh: '强化双手武器(Fortify Two-handed) : 增强自身双手武器的威力，持续一段时间。'},
    'Fortify One-handed': {price: 118, zh1: '强化单手武器', zh: '强化单手武器(Fortify One-handed) : 增强自身单手武器的威力，持续一段时间。'},
    'Fortify Heavy Armor': {price: 55, zh1: '强化重甲', zh: '强化重甲(Fortify Heavy Armor) : 增强自身重型装甲的防御力，持续一段时间。'},
    'Fortify Light Armor': {price: 55, zh1: '强化轻甲', zh: '强化轻甲(Fortify Light Armor) : 增强自身轻型装甲的防御力，持续一段时间。'},
    'Fortify Block': {price: 118, zh1: '强化格挡', zh: '强化格挡(Fortify Block) : 增强自身格挡技能的能力，持续一段时间。'},
    'Fortify Sneak': {price: 118, zh1: '强化潜行', zh: '强化潜行(Fortify Sneak) : 增强自身潜行技能的能力，持续一段时间。'},

    'Fortify Barter': {price: 48, zh1: '强化交易', zh: '强化交易(Fortify Barter) : 增强自身交易技能的能力，持续一段时间。'},
    'Fortify Carry Weight': {price: 208, zh1: '强化负重', zh: '强化负重(Fortify Carry Weight) : 增强自身的负重能力，持续一段时间。'},
    'Fortify Lockpicking': {price: 25, zh1: '强化开锁', zh: '强化开锁(Fortify Lockpicking) : 增强自身的开锁能力，持续一段时间。'},
    'Fortify Pickpocket': {price: 118, zh1: '强化偷窃', zh: '强化偷窃(Fortify Pickpocket) : 增强自身的偷窃能力，持续一段时间。'},
    'Fortify Enchanting': {price: 14, zh1: '强化附魔', zh: '强化附魔(Fortify Enchanting) : 增强自身的附魔能力，持续一段时间。'},
    'Fortify Smithing': {price: 82, zh1: '强化锻造', zh: '强化锻造(Fortify Smithing) : 增强自身的锻造能力，持续一段时间。'},
    'Invisibility': {price: 261, zh1: '隐身', zh: '隐身(Invisibility) : 让自己隐身，持续一段时间。'},
    'Waterbreathing': {price: 100, zh1: '水下呼吸', zh: '水下呼吸(Waterbreathing) : 让自己能在水下呼吸，持续一段时间。'},
    'Cure Disease': {price: 21, zh1: '治病', zh: '治病(Cure Disease) : 治愈一切疾病。'}
};